name: Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  checks:
    name: Check ${{ matrix.script }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        script: [lint, prettier, ts-check, test, build]
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: ${{ matrix.script }}
        run: pnpm ${{ matrix.script }}

  validate:
    name: PR Validation
    runs-on: ubuntu-latest
    needs: [checks]
    steps:
      - name: Log Success
        uses: actions/github-script@v7
        with:
          script: |
            console.log('Checks Passed')
