name: Pre-Release

# Adapted from the following workflow:
# https://github.com/cloudflare/next-on-pages/blob/main/.github/workflows/create-pullrequest-prerelease.yml

on:
  pull_request:
    branches: [main]

jobs:
  publish:
    name: Publish Pre-Release to Internal Registry
    if: ${{ github.repository_owner == 'james-elicx' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Set outputs
        id: hash
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Alter version
        run: pnpm alter-version ${{ steps.hash.outputs.sha_short }} PR=${{ github.event.number }}

      - name: Build
        run: pnpm build

      - name: Package
        run: pnpm pack

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: npm-package-build-output-router-${{ github.event.number }} # encode the PR number into the artifact name
          path: dist/build-output-router-*.tgz
